from __future__ import annotations

import sys
import unittest
from pathlib import Path

APP_ROOT = Path(__file__).resolve().parents[1]
if str(APP_ROOT) not in sys.path:
    sys.path.insert(0, str(APP_ROOT))


class PublicWwwLayoutTests(unittest.TestCase):
    def test_index_html_references_static_assets_and_programme_first_regions(self) -> None:
        text = (APP_ROOT / "public_www" / "index.html").read_text(encoding="utf-8")
        self.assertIn('href="assets/styles.css"', text)
        self.assertIn('src="assets/app.js"', text)
        self.assertIn("Parallel Sessions", text)
        self.assertNotIn("Paper sessions only.", text)
        self.assertIn('src="assets/logos/WIC-logo.png"', text)
        self.assertIn('src="assets/logos/Logos-partners-768x414.png"', text)
        self.assertIn('class="conference-logo-card"', text)
        self.assertIn('class="site-footer"', text)
        self.assertIn('data-view="programme"', text)
        self.assertIn('href="https://inequalitylab.world/www-site/uploads/2026/04/2026-WIC-Programme.pdf"', text)
        self.assertIn('target="_blank"', text)
        self.assertIn('data-view="papers"', text)
        self.assertIn('id="day-switcher"', text)
        self.assertIn('id="programme-toolbar"', text)
        self.assertIn('class="programme-tools"', text)
        self.assertIn('id="programme-view"', text)
        self.assertNotIn('id="plenary-view"', text)
        self.assertIn('id="papers-view"', text)
        self.assertIn('id="download-link"', text)
        self.assertIn('href="programme.xlsx"', text)
        self.assertIn('id="download-pdf-link"', text)
        self.assertIn('href="programme.pdf"', text)
        self.assertIn("Download PDF", text)
        self.assertIn("2026-WIC-Programme.pdf", text)
        self.assertNotIn("#view=FitH", text)
        self.assertNotIn('class="plenary-frame"', text)
        self.assertIn('id="session-detail-template"', text)
        self.assertIn('id="talk-row-template"', text)
        self.assertIn('class="talk-title talk-title-link"', text)
        self.assertIn('class="abstract-toggle"', text)

    def test_stylesheet_contains_editorial_and_responsive_hooks(self) -> None:
        text = (APP_ROOT / "public_www" / "assets" / "styles.css").read_text(encoding="utf-8")
        self.assertIn("--paper-bg", text)
        self.assertIn("--ink", text)
        self.assertIn("--coral", text)
        self.assertIn(".brand-row", text)
        self.assertIn(".conference-logo-card", text)
        self.assertIn(".partner-logo-card", text)
        self.assertIn(".site-footer", text)
        self.assertIn(".site-subtitle:empty", text)
        self.assertNotIn(".site-header::after", text)
        self.assertIn(".programme-tools", text)
        self.assertIn(".toolbar[hidden]", text)
        self.assertIn(".programme-block", text)
        self.assertIn(".programme-workspace", text)
        self.assertIn(".programme-workspace-layout", text)
        self.assertIn(".programme-workspace-layout.has-panel", text)
        self.assertIn(".programme-timetable-grid", text)
        self.assertIn(".programme-timetable-room", text)
        self.assertIn(".programme-timetable-time", text)
        self.assertIn(".programme-timetable-cell", text)
        self.assertIn(".session-panel", text)
        self.assertIn(".session-panel.is-open", text)
        self.assertIn(".programme-timetable-cell .session-room", text)
        self.assertIn(".session-card", text)
        self.assertIn(".talk-row", text)
        self.assertIn(".abstract-panel", text)
        self.assertIn(".talk-title-link", text)
        self.assertIn(".abstract-toggle", text)
        self.assertNotIn(".plenary-card", text)
        self.assertNotIn(".plenary-frame", text)
        self.assertIn("@media (max-width: 900px)", text)
        self.assertIn(".session-card:hover", text)
        self.assertIn(".session-card.is-expanded .session-summary", text)
        self.assertIn(".is-expanded", text)

    def test_app_js_contains_rendering_and_interaction_hooks(self) -> None:
        text = (APP_ROOT / "public_www" / "assets" / "app.js").read_text(encoding="utf-8")
        self.assertIn("fetch('data/programme.json')", text)
        self.assertIn("renderProgramme", text)
        self.assertIn("renderPapers", text)
        self.assertIn("renderDaySwitcher", text)
        self.assertIn("Parallel Sessions", text)
        self.assertNotIn("Paper sessions only.", text)
        self.assertIn("buildProgrammeMatrix", text)
        self.assertIn("renderProgrammeMatrix", text)
        self.assertIn("renderSessionPanel", text)
        self.assertIn("closeSessionPanel", text)
        self.assertIn("has-panel", text)
        self.assertIn("programme-timetable-grid", text)
        self.assertIn("session-panel", text)
        self.assertIn("toggleSession", text)
        self.assertIn("toggleAbstract", text)
        self.assertIn("click", text)
        self.assertIn("activeDay", text)
        self.assertIn("programme-view", text)
        self.assertIn("nav-link[data-view]", text)
        self.assertIn("querySelectorAll('.view')", text)
        self.assertIn("programme-toolbar", text)
        self.assertIn("presenter_display", text)
        self.assertIn("display_room", text)
        self.assertIn("display_presenter", text)
        self.assertIn("paper_url", text)
        self.assertIn("settings", text)
        self.assertIn("buildPaperTitleLink", text)
        self.assertIn("Show abstract", text)
        self.assertNotIn("paperLinkLabel", text)
        self.assertNotIn("cleanText(session.primary_theme)", text)
        self.assertNotIn("time.textContent = cleanText(session.time)", text)
        self.assertIn("pendingProgrammeFocus", text)
        self.assertIn("scrollIntoView", text)
        self.assertNotIn("renderStructureBlock", text)
        self.assertNotIn("mouseover", text)
        self.assertNotIn("hoveredAbstractId", text)


if __name__ == "__main__":
    unittest.main()
